#!/bin/sh

usage()
{
	echo "usage: osctree <host> <port> <path>"
	echo "    display a tree of available OSC methods at <host>:<port> under <path>"
}

#
# sanity checks
#

[ ! -f ./oscenum ] && {
	echo "hey man you've gotta compile oscenum first (read the README)";
	exit 1;
}

[ $# -lt 3 ] && {
	usage
	exit 1
}

#
# things
#

host=$1
port=$2
basepath=$3

enum()
{
	PATHS=`./oscenum $host $port $1`
	[ "$PATHS" = "" ] && return 0;

	for PATH in $PATHS; do
		enum $PATH && echo $PATH;
	done;

	return 1;
}

enum $basepath;
exit 0;
